---
title: "Final Project"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exploratory Analysis


```{r cars}
library(ggplot2)
library(tidyverse)
library(extracat)
library(tidyr)
library(dplyr)
library(lubridate)
library(vcd)
library(vcdExtra)
library(feather)
library(gridExtra)
library(reshape2)
library(ggpubr)
```


```{r}
reference_path <- "ml_papers_reference.feather"
papers_reference <- read_feather(reference_path)
summary(papers_reference)
```

```{r}
head(papers_reference)
```


```{r}
author_path <- "ml_papers_author.feather"
papers_authors <- read_feather(author_path)
summary(papers_authors)
```

```{r}
head(papers_authors)
```


```{r}
papers_reference_citation <- subset(papers_reference[!duplicated(papers_reference[c("id")]),], select = -c(references) )
head(papers_reference_citation)
```

# Number of papers

```{r}
ggplot(data=papers_reference_citation, aes(x=year)) +
    geom_bar(stat="count")
```

## Citation

```{r}
ggplot(data=papers_reference_citation, aes(x = n_citation)) + 
  geom_histogram(binwidth = 4, fill = 'cornflowerblue', color = 'grey') + 
  ggtitle("Number of Citations per Paper") +
  xlim(0, 100) +
  ylab("count") + 
  xlab("Number of Citations")
```

```{r}
ggplot(papers_reference_citation, aes(year, n_citation)) +
  geom_bar(stat="summary", fun.y="sum")
```

```{r}
citation_summary <- papers_reference_citation %>%
  group_by(year) %>%
  summarise_each(funs(mean, median), n_citation)

ggplot(melt(citation_summary, id.vars='year'), 
       aes(x=year, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge')
```

## Citation vs. Authors

```{r}
top_20_authors <- head(arrange(dplyr::summarise(group_by(papers_authors, authors),total_citation =sum(n_citation)), desc(total_citation)), n=20)

ggplot(top_20_authors, aes(x = total_citation, y = reorder(authors, total_citation))) +
  geom_point() + 
  ylab("authors") +
  xlim(0, 18500)
```

```{r}
top_10_authors <- head(arrange(dplyr::summarise(group_by(papers_authors, authors),total_citation =sum(n_citation)), desc(total_citation)), n=10)

papers_top_authors <- papers_authors %>% 
  filter(authors %in% top_10_authors$authors)

authors_citation <- dplyr::summarise(group_by(papers_top_authors, authors, year),yearly_citation =sum(n_citation))

cumsum_authors_citation <- authors_citation %>% group_by(authors) %>% mutate(cum_citations = cumsum(yearly_citation))

ggplot(cumsum_authors_citation, aes(year, cum_citations,colour=authors)) + 
  geom_line() +
  geom_point(size = 1) +
  ggtitle("Number of Citations of top Authors Over Time")
```

## Citation vs. Topic

```{r}
topic_freq <- dplyr::summarise(group_by(papers_reference_citation, year, topic),frequency =n())

ggplot(topic_freq, aes(year, frequency,colour=topic)) + 
  geom_line() +
  ggtitle("Number of Papers in each Topic Over Time")
```


```{r}
ggplot(papers_reference_citation, aes(n_citation, fill = topic, colour = topic)) +
  geom_density(alpha = 0.1) +
  xlim(0, 100)
```

## Citation vs. Venue

```{r}
ggplot(papers_reference_citation, aes(x = venue, y = n_citation)) + 
  geom_boxplot() +
  coord_flip() +
  ylim(0, 100)
```


## Citation vs. Title Length

```{r}
papers_reference_citation$title_length <- sapply(papers_reference_citation$title, function(x) length(unlist(strsplit(as.character(x), "\\W+"))))

ggplot(papers_reference_citation, aes(title_length, n_citation)) + 
  geom_point() +
  stat_cor(method = "pearson", papers_reference_citation.title_length = 3, papers_reference_citation.n_citation = 30)
```
